swagger: '2.0'
info:
  title: Eremetic
  description: Run one-off tasks on mesos
  version: "1.0.0"
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /api/v1/task:
    get:
      summary: List running tasks
      description: |
        List all running tasks, masking values in MaskedEnvironment.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: The name of the task. There can be several tasks with same name.
        - in: query
          name: state
          schema:
            type: string
          required: false
          description: The state of the task. Valid states are queued, active and terminated.
           Can be comma combined composite state e.g. "terminated,queued". The Default value
           is "active,queued". Empty string will return all states.
      responses:
        200:
          description: Task details
          schema:
            $ref: '#/definitions/Task'
        default:
          description: Unexpected error
    post:
      summary: Launch a task
      consumes:
        - application/json
      description: |
        The task endpoint lets you launch a task on mesos by submitting a payload describing the task to be run.
      parameters:
        - name: Task definition
          in: body
          description: Details of task to launch
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        202:
          description: Task ID
          schema:
            type: string
        default:
          description: Unexpected error
  /api/v1/task/{taskId}:
    get:
      summary: Get status of task
      description: |
        Check the status of task previously launched.
      parameters:
        - name: taskId
          in: path
          description: Task identifier
          required: true
          type: string
      responses:
        200:
          description: Task details
          schema:
            $ref: '#/definitions/Task'
        404:
          description: Task not found
        default:
          description: Unexpected error
definitions:
  Volume:
    type: object
    properties:
      container_path:
        type: string
        description: Path in container to mount at
      host_path:
        type: string
        description: Path on host to mount
  URI:
    type: object
    properties:
      uri:
        type: string
        description: URI to fetch
      extract:
        type: boolean
        description: True if the file should be extracted after being fetched
      executable:
        type: boolean
        description: True if the file should be flagged as executable
      cache:
        type: boolean
        description: True if the file should be cached
  Tasks:
    type: array
    items:
      $ref: '#/definitions/Task'
  Task:
    type: object
    required:
      - image
      - command
      - cpu
      - mem
    properties:
      id:
        type: string
        readOnly: true
        description: ID of task
      name:
        type: string
        description: Name of task
      image:
        type: string
        description: Full tag or hash of container to run
      command:
        type: string
        description: Command to run in the docker container
      force_pull_image:
        type: boolean
        description: Docker image will be pulled before each task launch
      privileged:
        type: boolean
        description: Docker will run the container in 'privileged' mode giving it all capabilities
      network:
        type: string
        description: Network mode to pass to the container
      dns:
        type: string
        description: DNS to be used by the container
      args:
        type: array
        items:
          type: string
        description: arguements to pass to the docker container entrypoint
      cpu:
        type: number
        description: Fractions of a CPU to request
      mem:
        type: number
        description: memory to use (MiB)
      volumes:
        type: array
        items:
          $ref: '#/definitions/Volume'
      volumes_from:
        type: array
        items:
          type: string
        description: container names to get volumes from
      fetch:
        type: array
        items:
          $ref: '#/definitions/URI'
      env:
        type: object
        description: Environment variables to set
      masked_env:
        type: object
        description: Environment variables to set but that are masked in any GET request.
      labels:
        type: object
        description: Labels for the task
      callback_uri:
        type: string
        description: URL to post a callback to
      framework_id:
        type: string
        readOnly: true
        description: Framework ID used when launching task
      agent_id:
        type: string
        readOnly: true
        description: Id of slave where task is running
      hostname:
        type: string
        readOnly: true
        description: Name of host where task is launched
      retry:
        type: number
        readOnly: true
        description: Number of times a retry have been attempted
      status:
        type: array
        readOnly: true
        items:
          type: object
          properties:
            status:
              type: string
              description: Status identifier
              enum:
                - TASK_STAGING
                - TASK_RUNNING
                - TASK_FINISHED
                - TASK_FAILED
                - TASK_LOST
                - TASK_ERROR
            time:
              type: number
              description: Unix timestamp of status change
