language: go

go:
 - 1.4
 - 1.5
 - 1.6

env:
 - PUBLISH_VERSION=1.6

services:
 - docker

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
 - make eremetic
 - overalls -project=github.com/klarna/eremetic -covermode=count
 - goveralls -coverprofile=overalls.coverprofile -service travis-ci

after_success:
 - misc/docker.sh
